# Generated by Django 6.1 on 2026-08-31 10:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyIntake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chief_complaint', models.TextField(blank=True)),
                ('triage_priority', models.CharField(choices=[('CRITICAL', 'Critical'), ('URGENT', 'Urgent'), ('STANDARD', 'Standard')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('intake_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_intake', to='patients.patientprofile')),
            ],
        ),
    ]
