# Generated by Django 6.1 on 2026-08-31 10:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mrn', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Medical Record Number')),
                ('date_of_birth', models.DateField()),
                ('device_id', models.CharField(blank=True, help_text='Wearable/monitoring device serial number.', max_length=64)),
                ('primary_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_patients', to='doctors.doctorprofile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField(help_text='When the device captured the reading.')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('heart_rate_bpm', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('systolic_bp', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('diastolic_bp', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('temperature_c', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('spo2_percent', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='patients.patientprofile')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
    ]
